![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [64]:
# Import necessary packages
import pandas as pd
import numpy as np

airbnb_price=pd.read_csv("data/airbnb_price.csv")
airbnb_last_review=pd.read_csv("data/airbnb_last_review.tsv", sep="\t")
airbnb_room_type=pd.read_excel("data/airbnb_room_type.xlsx")

In [65]:
airbnb_last_review.head()

   listing_id    host_name   last_review
0        2595     Jennifer   May 21 2019
1        3831  LisaRoxanne  July 05 2019
2        5099        Chris  June 22 2019
3        5178     Shunichi  June 24 2019
4        5238          Ben  June 09 2019

In [66]:
airbnb_last_review["last_review"] = pd.to_datetime(airbnb_last_review["last_review"]).dt.date
earliest_review=airbnb_last_review["last_review"].min()
most_recent_review=airbnb_last_review["last_review"].max()
most_recent_review

datetime.date(2019, 7, 9)

In [67]:
airbnb_room_type.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   description  25199 non-null  object
 2   room_type    25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB

In [68]:
airbnb_room_type["room_type"].value_counts()

Entire home/apt    8458
Private room       7241
entire home/apt    2665
private room       2248
ENTIRE HOME/APT    2143
PRIVATE ROOM       1867
Shared room         380
shared room         110
SHARED ROOM          97
Name: room_type, dtype: int64

In [69]:
airbnb_room_type["room_type"]=airbnb_room_type["room_type"].str.lower()
airbnb_room_type["room_type"].value_counts()

entire home/apt    13266
private room       11356
shared room          587
Name: room_type, dtype: int64

In [70]:
private_rooms_count=airbnb_room_type["room_type"].value_counts()[1]

In [71]:
airbnb_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   price        25209 non-null  object
 2   nbhood_full  25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB

In [72]:
airbnb_price.head()

   listing_id        price                nbhood_full
0        2595  225 dollars         Manhattan, Midtown
1        3831   89 dollars     Brooklyn, Clinton Hill
2        5099  200 dollars     Manhattan, Murray Hill
3        5178   79 dollars  Manhattan, Hell's Kitchen
4        5238  150 dollars       Manhattan, Chinatown

In [73]:
airbnb_price["price"]=airbnb_price["price"].str.replace(r"dollar(s)?","",regex=True).str.strip()
airbnb_price["price"]=airbnb_price["price"].astype("int")
airbnb_price["price"].unique()

array([ 225,   89,  200,   79,  150,  135,   85,  140,  215,   99,  130,
         80,  110,  120,   60,   44,  180,   50,   52,   55,   70,   40,
         68,  151,  228,  144,   69,   49,  250,  275,   51,   65,  105,
        190,   95,  145,  285,   94,  131,   98,  175,  500,  101,  125,
        100,   59,  325,  235,  170,  185,  115,   77,   76,  160,  195,
        156,  219,  165,  196,  350,   90,   75,  299,   83,  123,  265,
        249,  121,   45,   71,  199,   64,  159,  189,  239,  305,  155,
         92,   36,   37,  205,   39,  390,  129,  212,  124,  122,  109,
        575,  169,  179,  349,  139,   67,  211,  290,  395,   97,  259,
        295,  451,  300,  255,   72,   88,   42,  198,   46,   33,   91,
        400,  429,   43,  149,  248,   41,  230,  146,  116,  220,  288,
        438,  279,  137,  226,  154,  700,  850,   54,  495,  760,  153,
         73,  167,   96,   34,   93,  402,  800,  240,  209,  157,   86,
        106,   87,   56,  549,   20,  104,  298,  147,  269,  229,  119,
        138,  208,   58,  142,  174,  210,  311,   82,  450,  328,  102,
        385,  499,  107,  118,  280,  133,  128,   35,  136,  148,  433,
         61,  234,  595,  197,  127,  113,  108,  141,   62,  550,  380,
         84,   78,  900,  399,  330,  375,  168,   66,  103,  312,   38,
        158,  465,   81,   57,  260,  289,  176,   30,  339,  191, 2500,
         63,   53,  134,  420,  187,  950, 1000, 1395,  425,   47,  182,
        650,   48,  152,  117,  181,  188,  111,  162,  171,  112,  345,
        224,  194,   31,   74,  439,  555,   29,  245,  455,  193,  201,
        525,  600,  173,   32,  750,  480,  164,  177,  320,  340,  221,
       1485,   25,  218,  430,  126,  270,   16,  166,  785,  316,  318,
        273,  365,  184,  192,  216,  172,  246,  383,  419, 1050,  178,
        310,  985,  360,  699,  163, 1500,  272,  895,  258,  254,  795,
        995,  308,   27,  825,  524,  475,  244,  114,  132, 1200,  341,
        369,  322,  276,  247,  379,  440,  888, 2000,  222,  243,  398,
        355,  370,   22,  238, 1195,  999,  469,   28,  207,  410,  261,
        899,  161,  296,  531,  214,  335,  186,  799,  206,   26,  485,
        315,  143,  204, 1731,  319,  283, 1100,  814,  690,  619,  625,
        333,  359,  436,  274,  376,  329,  202,  408,  479,  294,  252,
        672,  415,  584,  183,  449, 1020,   19,  232,   11,  233,  459,
        489,  545, 2250,  227,  484, 1475,  278,   10,  615,  287, 1067,
        578,  236,  352,  256,  389,  264,  789,  585, 1795,  268, 1095,
        217,    0,  409,  496,  422,  435, 1177,  790,  378,  766,  231,
        840,  540,  237,  589,  949,  358, 2200, 1066,   12,  460,  487,
        647,  277, 3000,   23,  490,  416,  257,  374, 2990,  620,  649,
        412,   21,  975,  599,  344,  347,  393,  745,  309,   15, 1250,
        737,  689,  394,  639,  530,  848,  590,  403,  471,  478,   24,
        860, 1115,  520,  692,  241,  267, 5000,  714,  675,  266,  303,
        670,  418,  452,  343,  334,  321,  282,  332,  314,  453,  313,
        805,  443,  392,  284,  432,  444,  262,  263, 1075,  820, 1750,
        251, 1299, 1295,  519,  890,  404,  503,  472,  454,  203,  377,
        431,  505,  242,  468,  396,  498,  223,  612,  488, 1497,  515,
        990,  388,  407,  506,  324,  304, 3613, 2600,  293,  336,  560,
       5100,  898,  327,  470,  442,  306,  474,  616,  945,  539,  577,
         18,  367,  583,  659,   13, 7500,  447,  695, 1099,  428,  445,
        348, 2995,  342,  843,  213,  417, 1400,  323])

In [74]:
average_price=airbnb_price["price"].mean().round(2)
average_price

141.78

In [75]:
review_dates=pd.DataFrame({
    'first_reviewed':[earliest_review],
    'last_reviewed': [most_recent_review],
    'nb_private_rooms': [private_rooms_count],
    'avg_price': [average_price]
})